# Generated by Django 3.1.6 on 2021-02-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_spj', models.CharField(max_length=255)),
                ('pembuat', models.CharField(max_length=255)),
                ('tgl_pembuatan', models.DateField(auto_now_add=True)),
                ('tgl_perubahan_terakhir', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uraian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat_ke', models.IntegerField(default=0)),
                ('tgl_pembuatan', models.DateField(auto_now_add=True)),
                ('tgl_perubahan_terakhir', models.DateField(auto_now=True)),
                ('spj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spj')),
            ],
        ),
    ]
